version: "3.8"
services:
  breitband-desktop:
    image: fabianbees/breitbandmessung:latest
    container_name: breitband-desktop
    environment:
      - TZ=Europe/Berlin
      - TIME_START="13:00"
      - TIME_END="22:30"
      - HOMEASSISTANT_URL_DISABLE
      - HOMEASSISTANT_URL_ENABLE
      - HOMEASSISTANT_TOKEN
    volumes:
      - $PWD/breitbandmessung/data:/config/xdg/config/Breitbandmessung
    ports:
      - 5800:5800
    restart: unless-stopped